import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/mode-toggle";
import { notFound } from "next/navigation";
import { locales, useTranslations } from "@/lib/translations";
import LanguageToggle from "@/components/ui/language-toggle";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;

  return {
    title: "Uneseule AI Frontend",
    description: "Generated by create next app",
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // 지원하지 않는 locale인 경우 404 처리
  if (!locales.includes(locale as any)) {
    notFound();
  }

  const t = useTranslations(locale as any);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased fade-in`}
        data-locale={locale}
      >
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="border-b border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex justify-between items-center h-16">
                  <div className="flex items-center space-x-8">
                    <Link
                      href={`/${locale}`}
                      className="text-xl font-semibold text-gray-900 dark:text-white hover:text-gray-700 dark:hover:text-gray-300"
                    >
                      Uneseule AI
                    </Link>
                    <nav className="hidden md:flex space-x-6">
                      <Link
                        href={`/${locale}`}
                        className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
                      >
                        {t("navigation.home")}
                      </Link>
                      <Link
                        href={`/${locale}/service`}
                        className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
                      >
                        {t("navigation.service")}
                      </Link>
                    </nav>
                  </div>
                  <div className="flex items-center space-x-4">
                    <SignedOut>
                      <SignInButton />
                      <SignUpButton />
                    </SignedOut>
                    <SignedIn>
                      <UserButton />
                    </SignedIn>
                    <LanguageToggle />
                    <ModeToggle />
                  </div>
                </div>
              </div>
            </header>
            <main className="min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-white page-transition">
              {children}
            </main>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
